version: '3.8'

networks:
  default:

services:
  mysql-db:
    container_name:  mysql-db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'flightmissions'
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql:rw
      - ./mysql-db:/docker-entrypoint-initdb.d/
    networks:
      - default

  nestjs-app:
    container_name: nestjs-app
    depends_on:
      - mysql-db
    links:
      - mysql-db
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=flightmissions
      - DB_PORT=3306
    stdin_open: true
    tty: true
    volumes:
      - ./nestjs-app:/app
      - /app/node_modules
    networks:
      - default


volumes: 
  mysql-volume: